# Generated by Django 4.1.7 on 2023-02-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=42)),
                ("recipient", models.CharField(max_length=42)),
                ("value_sent", models.IntegerField()),
            ],
        ),
    ]
